### ISSUE TITLE
Поддержка Bootstrap4

### ISSUE THREAD

**Issue by chernyshevin** [jino5577/yii2-date-range-picker#3]
Привет. Пару лет пользуюсь вашим yii2-date-range-picker. Недавно переводил свой проект на Bootstrap4.
Потребовалась такая правка: https://github.com/chernyshevin/yii2-date-range-picker/commit/c23db30644a7b14b14f67089e7f0da3bf0c6cc82

Если я правильно понимаю то она перебивает указанный глобальный Asset проекта и как следствие на тех страницах где используется - едет вёрстка.

Понятно, что в master это изменение вливать не правильно, но может создадите отдельный бранч под это?
Или есть другой способ это обойти?

**Comment by nbogol** [comment]
Уже года 3 как я не занимаюсь этим.

- Nikolay Bogolubov
+1 (201) 207-8002 (mobile)

**Comment by chernyshevin** [comment]
> Уже года 3 как я не занимаюсь этим.

Очень жаль =(
Тогда решим локально =)
Спасибо за ответ!
